# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dcb8de2171b79d86ca273d235e9cbf2a21d981f19c007a703e7eeb9d4409ee2df48a55476c5be9ce2d8801516fc5346142bfd66be59d35f141ebfb78e4a2ec1

test:
  secret_key_base: 59bcd491e73c1bed17b66e5b24c21532181cadc53d660ade37352ba59f87f8d93840004e0ebb824f5ed0e7728dc46f224d1da5eb490d2c0b0aef34070f04de1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
